name: thomasrossphoto
favicon: null
layout_spectrum: 0.75158
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfaf8'
    - '#a6bea8'
    - '#392e10'
    - '#dedad3'
    - '#655e48'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
